### ISSUE TITLE
Creating Digital Clock at Homepage

### ISSUE THREAD

**Issue by harunaltunhr** [Mohammad-Musa/JS-Clock-#2]
- [X] Create a new branch called as `clock `
- [X] Create logic function for digital clock in `logic/starter.js`
- [X] Create global variables (if you need)
- [X] Create handler (if you need)
- [X] Create listener (if you need)
- [X] Make a PR, assign reviewers, and merge to master when completed

**Comment by Mohammad-Musa** [comment]
Everything is fine and it works perfectly but we have on issue:
for instance if the current time is 02:09:03 the clock that we have shows the time like this : 2:9:3.
it ignores adding (0) before the digit in case we have one digit.
could you fix it please by adding a function to handle the time when it has one digit by adding 0 before it!
thank you :)
